-- sql/09_governance/03_search_optimization.sql
USE ROLE DE_ADMIN;
USE SCHEMA SALES_DB.RAW;

ALTER TABLE SALES ADD SEARCH OPTIMIZATION ON EQUALITY(transaction_id);

-- Confirm it's building/enabled
SELECT SYSTEM$ESTIMATE_SEARCH_OPTIMIZATION_COSTS('SALES');
DESCRIBE SEARCH OPTIMIZATION ON SALES;